# Generated by Django 5.2.7 on 2025-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='YoE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
